/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import * as THREE from 'three'
import {  EffectComposer, SelectiveBloom } from "@react-three/postprocessing";

const sceneTexture = new THREE.TextureLoader().load('./img/scene22.jpg');

sceneTexture.magFilter =  THREE.LinearFilter
sceneTexture.encoding = THREE.sRGBEncoding

export default function FinalWatch({ ... props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/finalWatch.glb");

  const inner = useRef();
  const outer = useRef();

  const clockSphere = useRef();
  const pLight1 = useRef();
  const pLight2 = useRef();

    const scene = useThree();
   
  useEffect(()=> {
        scene.scene.background = sceneTexture;
        
  }, []);

  useFrame(({clock}) => {
        inner.current.rotation.y = -clock.getElapsedTime() * 0.15;
        outer.current.rotation.y = -clock.getElapsedTime() * 0.25;
        group.current.position.y = (Math.sin(clock.getElapsedTime()) * 0.01)
  })



  return (
    <group 
    ref={group} {...props} 
    dispose={null}
    scale={0.035}
    rotation={[0, Math.PI / 2, 0]}
    name={"Watch"}
    >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[0.65, -0.26, 3.97]}
        rotation={[1.55, 0.14, 0]}
        scale={[0.8, -0.08, 0.8]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={nodes.Cylinder001.material}
          position={[-1.5, 0, -0.85]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FinalStrap1_MenMetal2_0.geometry}
        material={materials.MenMetal2}
        position={[0, -0.1, 0.45]}
        rotation={[1.54, 0, 0]}
        scale={0.71}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.strapClip_MenMetal2_0.geometry}
          material={materials.MenMetal2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FinalStrap1_MenMetal_0.geometry}
          material={materials["MenMetal.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FinalStrap2_MenMetal_0.geometry}
          material={materials["MenMetal.007"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.FinalStrap2_MenMetal2_0.geometry}
          material={materials.MenMetal2}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.sphereOne}
        position={[0, 0.01, 3.86]}
        rotation={[-0.02, 0, 0]}
        scale={[2.05, 2.08, 0.18]}
        ref={ clockSphere }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WatchCubeSecond.geometry}
        material={materials.FrontMetal}
        position={[0, -0.01, 4.32]}
        rotation={[1.55, -0.78, -Math.PI / 2]}
        scale={[0.08, 2.71, 2.71]}
        ref={ inner }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.frameMaterial}
        position={[0, 0, 3.84]}
        rotation={[-0.02, 0, 0]}
        scale={[2.31, 2.18, 0.32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.WatchCubeOne.geometry}
        material={materials.FrontMetal2}
        position={[0, -0.01, 4.15]}
        rotation={[1.55, -0.27, -Math.PI / 2]}
        scale={[0.08, 2.71, 2.71]}
        ref={ outer }
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials["MenMetal.007"]}
        position={[0, -0.01, 4.2]}
        rotation={[1.55, 0, 0]}
        scale={[0.12, 0.2, 0.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.MenMetal}
        position={[0, -0.01, 3.76]}
        rotation={[-0.02, 0, 0]}
        scale={[2.76, 2.76, 0.31]}
      />

        <EffectComposer autoClear={false} >
            <SelectiveBloom
            lights={[pLight1, pLight2]}
            selection={[  clockSphere ]}
            intensity={2.0}
            
            luminanceThreshold={0.0001}
            luminanceSmoothing={0.75} 
            />
         
        </EffectComposer>
      <pointLight ref={pLight1} intensity={1.0} color={0x6031E7} position={[35, 0, -50]} />
      <pointLight ref={pLight2} intensity={1.0} color={'blue'} position={[-35, 0, -50]}  />
    </group>
  );
}

useGLTF.preload("/finalWatch.glb");
